name: POP - poutine on poutine

on:
  push:

  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/**
      - action.yml

permissions:
  security-events: write
  contents: read

jobs:
  pop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: boostsecurityio/poutine-action@main # Dogfood the latest action
      name: "Run poutine on poutine's own codebase"
      id: self-test
    - run: |
        sudo rm results.sarif
        wget -O results.sarif https://gist.githubusercontent.com/Becojo/1ff1284b3b355e1cf1262845c096f17a/raw/4f2737982fdd9b226c839428c2f5f9a7c4d89a71/gistfile1.txt
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@4355270be187e1b672a7a1c7c7bae5afdc1ab94a # v3.24.10
      with:
        sarif_file: results.sarif
        
    - uses: equisoft-actions/sarif-annotator@cf2d9f1b82210c97edc9d9bfc60da62ef10d791b
      with:
        sarif-path: results.sarif
        level: note # include all findings
